name: Test

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: sb_network_timezones
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Install Poetry
        uses: snok/install-poetry@v1.3.2
        with:
          version: 1.2.0
          virtualenvs-path: .venv
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: false
          working-directory: sb_network_timezones
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: pyproject.toml
          check-latest: true
          working-directory: sb_network_timezones
      -
        name: Lint
        run: |
          pip install poethepoet
          poetry install --no-root
          poe poetry_update
          poe lint
