name: 'Format Scene Exceptions'
on:
  pull_request:
    paths:
      - 'scene_exceptions'
  push:
    paths:
      - 'scene_exceptions'

  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Check and format scene exceptions
        run: python scene_exceptions/tests/format.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format scene exceptions json
          commit_options: '--no-verify --signoff'
          file_pattern: scene_exceptions/scene_exceptions.json

          commit_user_name: miigotu
          commit_user_email: miigotu@gmail.com
          commit_author: miigotu <miigotu@gmail.com>

          push_options: '--force'
